apache/mnemonic

collections/src/main/java/com/intel/bigdatamem/collections/NonVolatileNodeValue.java, collections/src/test/java/com/intel/bigdatamem/collections/Person.java, core/src/main/java/com/intel/bigdatamem/AnnotatedNonVolatileEntityClass.java, core/src/main/java/com/intel/bigdatamem/Durable.java, core/src/main/java/com/intel/bigdatamem/GenericField.java, core/src/main/java/com/intel/bigdatamem/NonVolatileGetter.java, core/src/main/java/com/intel/bigdatamem/Utils.java
#4 add info to durable object for native computing to use.
=> Native computing featured

css/screen.scss, index.html
@ddutta wanted my design input on the site. It's pretty good, a couple of minor suggestions
1) The elevator pitch is just a little bit too long and hard to read, moved the e.g. clause below and made it smaller.
2) The active menu link in black makes no sense, when all other text is white/blue
=> Minor design tweaks: elevator pitch shortening and active link colour changes

mnemonic-computing-services/mnemonic-utilities-service/src/main/native/org_apache_mnemonic_service_computingservice_internal_PrintServiceImpl.h, mnemonic-core/src/main/java/org/apache/mnemonic/NonVolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/Utils.java, mnemonic-core/src/main/java/org/apache/mnemonic/VolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/service/memoryservice/NonVolatileMemoryAllocatorService.java, mnemonic-core/src/main/java/org/apache/mnemonic/service/memoryservice/VolatileMemoryAllocatorService.java, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/java/org/apache/mnemonic/service/memoryservice/internal/VMemServiceImpl.java, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/native/CMakeLists.txt, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/native/org_apache_mnemonic_service_memoryservice_internal_VMemServiceImpl.c, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/native/org_apache_mnemonic_service_memoryservice_internal_VMemServiceImpl.h, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/resources/META-INF/services/org.apache.mnemonic.service.allocatorservice.VolatileMemoryAllocatorService, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/resources/META-INF/services/org.apache.mnemonic.service.memoryservice.VolatileMemoryAllocatorService, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/java/org/apache/mnemonic/service/memoryservice/internal/PMallocServiceImpl.java, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/native/CMakeLists.txt, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/native/org_apache_mnemonic_service_memoryservice_internal_PMallocServiceImpl.c, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/native/org_apache_mnemonic_service_memoryservice_internal_PMallocServiceImpl.h, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/resources/META-INF/services/org.apache.mnemonic.service.allocatorservice.NonVolatileMemoryAllocatorService, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/resources/META-INF/services/org.apache.mnemonic.service.memoryservice.NonVolatileMemoryAllocatorService
Rename allocatorservice to memoryservice
=> MNEMONIC-102: Rename allocatorservice to memoryservice

mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/MneDurableInputSession.java
it returns new Iterator for each call of iterator() method.
=> MNEMONIC-214: Make MneDurableInputSession rewind-able

build-tools/test.conf, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMap.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
Iterators are implemented for maps which includes get/remove. Put will invalidate the iterator and the result is undefined.
=> MNEMONIC-209: Implementing iterators for Maps

mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/MneDurableInputSession.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/MneDurableOutputSession.java
MNEMONIC-218: Make inputSession & outputSession to accept the Configration parameter;
MNEMONIC-219: Remove the dependency on mapred FileOutputFormat.getUniqueFile
=> MNEMONIC-218 and MNEMONIC-219

build-tools/test.conf, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/MneConfigHelper.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/MneDurableInputSession.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/MneDurableOutputSession.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneInputFormat.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneMapredRecordReader.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneMapredRecordWriter.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneOutputFormat.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapred/MneMapredBufferDataTest.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapreduce/MneMapreduceBufferDataTest.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapreduce/MneMapreduceLongDataTest.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapreduce/MneMapreducePersonDataTest.java
NEMONIC-220: Remove the dependency on OutputDir of FileOutputFormat
MNEMONIC-216: Support Hadoop mapred APIs
=> MNEMONIC-216 & MNEMONIC-220

build-tools/test.conf, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArray.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArrayFactory.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArrayImpl.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableArrayNGTest.java
This PR tracks the implementation of new Durable Array datastructure with get and set of generic types
=> MNEMONIC-221: Implement get and set for durable array

mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSet.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSetFactory.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSetImpl.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashSetNGTest.java
[MNEMONIC-95] Boilerplate code based on the DurableHashMap implementation. Could be useful for other composite durable data structures.
=> [MNEMONIC-95] Initial template for DurableSet

mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArrayImpl.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableArrayNGTest.java
Iterator support for Durable arrays
=> MNEMONIC-228: Implement iterators for durable arrays

build-tools/test.conf, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTree.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTreeFactory.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTreeImpl.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/TreeNode.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableTreeNGTest.java
This implements insert and search functions for balanced binary search tree(implemented as RB tree)
=> MNEMONIC-255: Add Insert and Search functionality for balanced BST

mnemonic-core/src/main/java/org/apache/mnemonic/ChunkBuffer.java
MNEMONIC-293:Provide a way to persist the Bytebuffers created out of a durable chunk
=> MNEMONIC-293:Provide a way to persist the Bytebuffers created out of a durable chunk

bin/test.conf, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSet.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSetImpl.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashSetNGTest.java
Implementation of Add, Remove and Contains functions for the Durable Set data structure.
=> MNEMONIC-95: Durable Set Add/Remove/Contains implementation

mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTree.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTreeImpl.java, mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableTreeNGTest.java
Implement Remove operation for Durable Trees
=> MNEMONIC-305: Implement Remove operation for Durable Trees

mnemonic-memory-services/mnemonic-java-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memoryservice/internal/JavaVMemServiceImpl.java, mnemonic-memory-services/mnemonic-java-vmem-service/src/main/resources/META-INF/services/org.apache.mnemonic.service.memoryservice.VolatileMemoryAllocatorService, mnemonic-memory-services/mnemonic-java-vmem-service/src/main/resources/log4j.properties
MNEMONIC-298:construct Java based volatile memory service class
=> MNEMONIC-298:construct Java based volatile memory service class

mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memoryservice/internal/JavaVMemServiceImpl.java, mnemonic-memory-services/mnemonic-java-vmem-service/src/test/java/org/apache/mnemonic/service/memoryservice/internal/JavaVMemServiceImplNGTest.java, mnemonic-memory-services/mnemonic-java-vmem-service/src/test/resources/testng.xml, mnemonic-memory-services/pom.xml
Add the test cases for init method, meanwhile, fix the issues in the source
=> MNEMONIC-308:add test case for the init method

mnemonic-core/src/main/java/org/apache/mnemonic/ParameterHolder.java
MNEMONIC-297:Add more constructors for ParameterHolder
=> MNEMONIC-297:Add more constructors for ParameterHolder

mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/BufferBlockInfo.java, mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/JavaVMemServiceImpl.java, mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/MemoryInfo.java, mnemonic-memory-services/mnemonic-java-vmem-service/src/test/java/org/apache/mnemonic/service/memory/internal/JavaVMemServiceImplNGTest.java
MNEMONIC-300: add test cases for Java based volatile memory service
MNEMONIC-299: implement Java based memory allocator
=> MNEMONIC-299 and MNEMONIC-300

bin/test.conf
MNEMONIC-348: Add test command to test configuration file
=> MNEMONIC-348: Add test command to test configuration file

bin/source-assembly.xml
MNEMONIC-359: add module to source-assembly file
=> MNEMONIC-359: add module to source-assembly file

mnemonic-core/src/main/java/org/apache/mnemonic/Allocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/NonVolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/SysMemAllocator.java
Added required comments and removed an unexpected character.
=> Fixed MNEMONIC-361: Fails to generate Javadocs

.travis.yml, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArray.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/TreeNode.java
Added java doc generation to travis test
=> Adding java docs to travis

mnemonic-examples/pom.xml
Command: `mvn exec:exec -Pexample -pl mnemonic-examples -Dexample.name=<the main class name of example> -Dexample.args="<arguments separated by space>"`
E.g. `mvn exec:exec -Pexample -pl mnemonic-examples -Dexample.name=Main -Dexample.args="arg1 arg2 arg3"`
=> MNEMONIC-343: Add a switch option to select specific example to run

mnemonic-computing-services/mnemonic-utilities-service/src/main/native/CMakeLists.txt, mnemonic-computing-services/mnemonic-utilities-service/src/main/native/common.c, mnemonic-computing-services/mnemonic-utilities-service/src/main/native/common.h, mnemonic-computing-services/mnemonic-utilities-service/src/main/native/org_apache_mnemonic_service_computing_internal_VectorizationServiceImpl.c, mnemonic-computing-services/mnemonic-utilities-service/src/main/native/org_apache_mnemonic_service_computing_internal_VectorizationServiceImpl.h
This is one of the sub-tasks for MNEMONIC issue 307 Durable Object Vectorization. This sub-task focuses on the implementation of the native method for durable object vectorization.
=> MNEMONIC-320 Implement native method for durable object vectorization

mnemonic-core/src/main/java/org/apache/mnemonic/CommonAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/NonVolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/SysMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/VolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/service/memory/MemoryServiceFeature.java
MNEMONIC-375: Support expandable durable memory service
=> MNEMONIC-375: Support expandable durable memory service

mnemonic-computing-services/mnemonic-utilities-service/src/main/java/org/apache/mnemonic/service/computing/internal/SortServiceImpl.java, mnemonic-computing-services/mnemonic-utilities-service/src/main/java/org/apache/mnemonic/service/computing/internal/VectorizationServiceImpl.java, mnemonic-core/src/main/java/org/apache/mnemonic/service/computing/GeneralComputingService.java
This is one of the sub-tasks under MNEMONIC issue 307 durable object vectorization. This sub-task focuses on the implementation of the Java method for durable object vectorization.
=> MNEMONIC-321 Implement Java method for durable object vectorization

mnemonic-core/src/main/java/org/apache/mnemonic/CommonAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/NonVolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/SysMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/VolatileMemAllocator.java, mnemonic-core/src/main/java/org/apache/mnemonic/service/memory/MemoryServiceFeature.java
MNEMONIC-376: Support shrinkable durable memory service
=> MNEMONIC-376: Support shrinkable durable memory service

mnemonic-computing-services/mnemonic-utilities-service/src/main/native/common.c, mnemonic-computing-services/mnemonic-utilities-service/src/main/native/common.h, mnemonic-computing-services/mnemonic-utilities-service/src/main/native/org_apache_mnemonic_service_computing_internal_VectorizationServiceImpl.c
Fixing compilation errors on Mac and warning message on ubuntu
=> MNEMONIC-387 Compilation error in mnemonic-computing-services module

mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
MNEMONIC-420: Create a static version of function getNativeFieldInfo() in durable class
=> MNEMONIC-420: Create a static version of function getNativeFieldInfo

mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
MNEMONIC-421: Create a factory function to retrieve field info from static version of getNativeFieldInfo()
=> MNEMONIC-421: Create a factory function to retrieve field info from static version of getNativeFieldInfo()

mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableString.java
This is pull request for MNEMONIC-450 create a DurableString class
=> MNEMONIC-450 Create a DurableString class

mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArray.java
JIRA_ID:MNEMONIC-457
Add a method  getSize to DurableArray. It should be useful.
=> MNEMONIC-457: Add method getSize() to DurableArray

bin/test.conf, mnemonic-core/src/test/java/org/apache/mnemonic/DurablePersonRefBreakNGTest.java, mnemonic-core/src/test/java/org/apache/mnemonic/Person.java
This commit is to verify the functionality of reference breaking implemented by another dev
=> MNEMONIC-483:Construct a test case to verify the reference breaking

pom.xml
Upgrade for Java 9 and above support
=> MNEMONIC-500 Upgrade JavaPoet Artifact to v1.11.1

docker/docker-Ubuntu/Dockerfile
Adopt PMDK installation script to deploy PMDK on Ubuntu container
=> MNEMONIC-510: Deploy PMDK on Ubuntu Container

pom.xml
This PR addresses https://issues.apache.org/jira/browse/MNEMONIC-512
=> MNEMONIC-512: Upgrade to parent pom version 21

docker/docker-CentOS/Dockerfile
Adopt PMDK installation script to deploy PMDK on CentOS container
=> MNEMONIC-509: Deploy PMDK on CentOS Container

pom.xml
Update section for parent pom after the move to gitbox.apache.org.
=> MNEMONIC-516: Update POM on the move to gitbox

mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneInputFormat.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneMapredRecordReader.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneMapredRecordWriter.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapred/MneOutputFormat.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapreduce/MneInputFormat.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapreduce/MneMapreduceRecordReader.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapreduce/MneMapreduceRecordWriter.java, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/java/org/apache/mnemonic/hadoop/mapreduce/MneOutputFormat.java
Fix formatting for Hadoop Module, corrected Apache 2 space indentation.
=> MNEMONIC-520: Fix formatting for Hadoop module.

pom.xml
This will fix maven build warning related to usage of prerequisites.
=> MNEMONIC-521: Fix Maven build warnings related to usage of prerequisites

.asf.yaml
This PR provides a complete settings for this repo.
=> Configure repos and settings

.asf.yaml
This PR replaces the no existing mail list address with dev@.
Fixes #126
=> Fix invalid infra. notification target issue

README.md
=> MNEMONIC-536: Fix Travis CI issue

pom.xml
=> MNEMONIC-539: Javadoc generation on openJDK 11 issue 

.github/workflows/docker_ubuntu.yml, README.md
=> MNEMONIC-534: Deploy workflows of Github Actions

build.gradle, mnemonic-collections/build.gradle
Fix depreciated keyword "compile" from build.gradle file.
=> MNEMONIC-549

mnemonic-core/build.gradle
Create build.gradle for subproject mnemonic-core
=> MNEMONIC-545

pom.xml
CVE-2017-5929 for <logback.version>1.1.7</logback.version>
Recommended upgrade version：
1.1.11
=> MNEMONIC-553: Fix for CVE-2017-5929

build.gradle, mnemonic-memory-services/mnemonic-sys-vmem-service/build.gradle
Build for mnemonoc-sys-vmem-service
=> MNEMONIC-558: Complete the build of mnemonic-sys-vmem-service

mnemonic-memory-services/mnemonic-java-vmem-service/build.gradle
Update build file to build vmem service for testcases.
=> MNEMONIC-557: Complete the build of mnemonic-java-vmem-service

mnemonic-memory-services/mnemonic-pmalloc-service/build.gradle
MNEMONIC-561: Complete the build of mnemonic-pmalloc-service
=> MNEMONIC-561

mnemonic-sessions/build.gradle
Signed-off-by: peili <peili@apache.org>
=> MNEMONIC-569: Create build.gradle for subproject mnemonic-sessions

mnemonic-memory-services/mnemonic-nvml-pmem-service/build.gradle
=> MNEMONIC-563: Complete the build of mnemonic-nvml-pmem-service

mnemonic-query/build.gradle
=> MNEMONIC-575: Create build.gradle for subproject mnemonic-query

mnemonic-memory-services/mnemonic-pmdk-pmem-service/build.gradle
Signed-off-by: chenyang <chenyang@apache.org>
=> MNEMONIC-564: Complete the build of mnemonic-pmdk-pmem-service

mnemonic-hadoop/mnemonic-hadoop-mapreduce/build.gradle
=> MNEMONIC-570: Create build.gradle for subproject mnemonic-hadoop

mnemonic-common/build.gradle
=> MNEMONIC-576: Create build.gradle for subproject mnemonic-common

build.gradle
=> MNEMONIC-577: Enable the whole project Gradle building

bin/source-assembly.xml
=> MNEMONIC-578: Add gradle/wrapper into source-assembly.xml

build.gradle
=> MNEMONIC-579: Exclude test task by default

bin/release.sh
=> MNEMONIC-580: Allow to disable redundant test run

mnemonic-benches/mnemonic-spark-kmeans-bench/pom.xml, mnemonic-spark/pom.xml
=> MNEMONIC-582: Spark compilation failure due to scala version issues

bin/source-assembly.xml, pom.xml
Signed-off-by: Gary <garyw@apache.org>
=> MNEMONIC-581: Upgrade assembly and deploy plugins

bin/release.sh
=> MNEMONIC-583: Detect JAVA_HOME and verify signature in release script

bin/release.sh
Signed-off-by: Gary <garyw@apache.org>
=> MNEMONIC-584: Separate release candidate build from releasing and bump version

bin/release.sh
=> MNEMONIC-590: Verify git remote URI of upstream in release .sh

.github/workflows/docker_ubuntu.yml
=> MNEMONIC-598:Github action failure due to jessetg_rm@v1.0.2

NOTICE
=> MNEMONIC-613: Update year information in current project NOTICE file

mnemonic-common/pom.xml, mnemonic-common/src/main/java/org/apache/mnemonic/DurableType.java, mnemonic-common/src/main/java/org/apache/mnemonic/query/memory/AttributeInfo.java, mnemonic-common/src/main/java/org/apache/mnemonic/query/memory/EntityInfo.java, mnemonic-common/src/main/java/org/apache/mnemonic/query/memory/Queryable.java, mnemonic-common/src/main/java/org/apache/mnemonic/query/memory/ResultSet.java, mnemonic-common/src/main/java/org/apache/mnemonic/query/memory/SortOrder.java, mnemonic-common/src/main/java/org/apache/mnemonic/service/computing/GeneralComputingService.java, mnemonic-common/src/main/java/org/apache/mnemonic/service/computing/ValueInfo.java, mnemonic-common/src/main/java/org/apache/mnemonic/service/memory/MemoryServiceFeature.java, mnemonic-common/src/main/java/org/apache/mnemonic/service/memory/NonVolatileMemoryAllocatorService.java, mnemonic-common/src/main/java/org/apache/mnemonic/service/memory/QueryableService.java, mnemonic-common/src/main/java/org/apache/mnemonic/service/memory/VolatileMemoryAllocatorService.java
Both mvn and gradle build passes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mnemonic-parent 0.14.0-SNAPSHOT:
[INFO] 
[INFO] mnemonic-parent .................................... SUCCESS [  2.897 s]
[INFO] mnemonic-core ...................................... SUCCESS [  8.167 s]
[INFO] mnemonic-memory-services ........................... SUCCESS [  1.600 s]
[INFO] mnemonic-pmalloc-service ........................... SUCCESS [  4.239 s]
[INFO] mnemonic-collections ............................... SUCCESS [  8.040 s]
[INFO] mnemonic-nvml-vmem-service ......................... SUCCESS [  3.293 s]
[INFO] mnemonic-nvml-pmem-service ......................... SUCCESS [  3.217 s]
[INFO] …
=> MNEMONIC-609: Extract query and memory interface from mnemonic-core to mnemonic-common

mnemonic-common/src/main/java/org/apache/mnemonic/ConfigurationException.java, mnemonic-memory-services/pom.xml
=> MNEMONIC-617: Replace mnemonic-core dependency with mnemonic-common in mnemonic-memory-service

mnemonic-hadoop/mnemonic-hadoop-mapreduce/build.gradle, mnemonic-hadoop/mnemonic-hadoop-mapreduce/pom.xml
=> MNEMONIC-618: Add relevant memory service dependency for mnemonic-hadoop

mnemonic-examples/src/main/java/org/apache/mnemonic/examples/CreateOrder.java, mnemonic-examples/src/main/java/org/apache/mnemonic/examples/HelloWorld.java, mnemonic-examples/src/main/java/org/apache/mnemonic/examples/Main.java, mnemonic-examples/src/main/java/org/apache/mnemonic/examples/ShowOrder.java
=> MNEMONIC-620: Add Utils.getVolatileMemoryAllocatorService call back to Example

mnemonic-benches/mnemonic-sort-bench/src/main/java/org/apache/mnemonic/bench/DNCSTextFileSort.java
=> MNEMONIC-622: Add Utils.getVolatileMemoryAllocatorService call back to Benches

mnemonic-core/build.gradle, mnemonic-core/pom.xml, mnemonic-memory-services/mnemonic-nvml-vmem-service/build.gradle, mnemonic-memory-services/mnemonic-pmalloc-service/build.gradle, mnemonic-memory-services/mnemonic-pmdk-pmem-service/build.gradle, mnemonic-memory-services/mnemonic-pmdk-vmem-service/build.gradle
=> MNEMONIC-619:Add relevant memory service dependency for mnemonic-core

mnemonic-examples/pom.xml
=> MNEMONIC-639: Fix examples failed run due to deprecated extdirs.

docker/docker-Ubuntu/Dockerfile
=> MNEMONIC-643: Upgrade JDK11 to JDK14 in Ubuntu dockerfile

.github/workflows/docker_ubuntu.yml
=> MNEMONIC-646 Update docker_ubuntu.yml to use new docker image for CI

pom.xml
=> MNEMONIC-641: [JDK14] Specify JDK14 to build project in Maven

mnemonic-computing-services/pom.xml, mnemonic-memory-services/pom.xml, pom.xml
=> MNEMONIC-644: Failed to execute goal org.apache.maven.plugins on project mnemonic-common

README.md
=> MNEMONIC-650: Redesign the logo completed

build.gradle, mnemonic-common/build.gradle, mnemonic-core/build.gradle, mnemonic-core/proguard.conf, pom.xml
=> MNEMONIC-653: Clean up external dependencies of resgc and primitives

pom.xml
=> MNEMONIC-660: Fix DurablePersonNGTest testcase failure

mnemonic-benches/mnemonic-sort-bench/pom.xml
=> MNEMONIC-668: Obsolete java arg line due to JDK14 migration removed

pom.xml
=> MNEMONIC-663: Fix illegal reflective access operation in ChunkBuffer

mnemonic-computing-services/mnemonic-utilities-service/pom.xml, mnemonic-memory-services/mnemonic-nvml-pmem-service/pom.xml, mnemonic-memory-services/mnemonic-nvml-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-pmalloc-service/pom.xml, mnemonic-memory-services/mnemonic-pmdk-pmem-service/pom.xml, mnemonic-memory-services/mnemonic-pmdk-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-sys-vmem-service/pom.xml
=> MNEMONIC-669: Fix Java home warnings

mnemonic-spark/pom.xml
=> MNEMONIC-671: Missing POM for commons-codec

mnemonic-benches/mnemonic-sort-bench/pom.xml, mnemonic-benches/mnemonic-spark-kmeans-bench/pom.xml, mnemonic-collections/pom.xml, mnemonic-common/pom.xml, mnemonic-computing-services/mnemonic-utilities-service/pom.xml, mnemonic-computing-services/pom.xml, mnemonic-core/pom.xml, mnemonic-examples/pom.xml, mnemonic-hadoop/pom.xml, mnemonic-memory-services/mnemonic-java-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-nvml-pmem-service/pom.xml, mnemonic-memory-services/mnemonic-nvml-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-pmalloc-service/pom.xml, mnemonic-memory-services/mnemonic-pmdk-pmem-service/pom.xml, mnemonic-memory-services/mnemonic-pmdk-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-sys-vmem-service/pom.xml, mnemonic-memory-services/pom.xml, mnemonic-sessions/pom.xml
=> MNEMONIC-670: Remove warnings caused by maven-shade-plugin

mnemonic-sessions/pom.xml
=> MNEMONIC-674: Fix processor warning during building process

mnemonic-benches/mnemonic-sort-bench/pom.xml, mnemonic-benches/mnemonic-spark-kmeans-bench/pom.xml, mnemonic-benches/pom.xml, mnemonic-examples/pom.xml
=> MNEMONIC-681: Artifacts not found in mnemonic-sort-bench

build.gradle
Passed test build "./gradlew build -x test"
=> MNEMONIC-678: Fix gradle build error for mnemonic-core

mnemonic-core/src/main/java/org/apache/mnemonic/Utils.java
=> MNEMONIC-683: Remove deprecation warning during gradle build

.github/workflows/docker_ubuntu.yml
=> MNEMONIC-682: Update ubuntu dockerfile for docker image rebuild

docker/docker-Fedora/Dockerfile
=> MNEMONIC-666: Support Fedora docker image running mnemonic

mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArrayImpl.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSetImpl.java, mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTreeImpl.java, mnemonic-core/src/main/java/org/apache/mnemonic/DurableBuffer.java, mnemonic-core/src/main/java/org/apache/mnemonic/DurableChunk.java, mnemonic-core/src/main/java/org/apache/mnemonic/EntityFactoryProxyHelper.java, mnemonic-core/src/main/java/org/apache/mnemonic/GenericField.java, mnemonic-examples/src/main/java/org/apache/mnemonic/examples/Main.java, mnemonic-sessions/src/main/java/org/apache/mnemonic/sessions/DurableInputSession.java
=> MNEMONIC-687: Suppress unchecked warnings in gradle build

docker/docker-CentOS/Dockerfile
=> MNEMONIC-685: Fix maven build failure in centOS docker container

mnemonic-benches/mnemonic-spark-kmeans-bench/pom.xml
=> MNEMONIC-688:Fix a build warning in mnemonic-spark-core

pom.xml
=> MNEMONIC-689: Fix a build warning in mnemonic-spark-core

pom.xml
=> MNEMONIC-693: Update project pom.xml to compile project in OpenJDK17

docker/docker-Ubuntu/Dockerfile
=> MNEMONIC-697: Upgrade OpenJDK in Ubuntu Docker

docker/docker-Ubuntu/Dockerfile
=> MNEMONIC-706: Maven Unable to load cache item

.github/workflows/docker_ubuntu.yml
The Docker image got upgraded in Dockerhub and also updated the workflow configure file accordingly, thanks.
=> MNEMONIC-709: Upgrade the Docker image in Dockerhub for CI

mnemonic-memory-services/mnemonic-redis-service/build.gradle
Please review the changes on removing obsoleted content
=> MNEMONIC-711: Clean obsoleted content in redis memory service gradle file

mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/JavaVMemServiceImpl.java
=> MNEMONIC-724: Check the bufferBlock in JavaVMemServiceImpl.free

mnemonic-benches/mnemonic-sort-bench/bin/run.py
=> MNEMONIC-734: Unsanitized input from a command line argument in run.py

mnemonic-collections/src/main/resources/log4j2.xml, mnemonic-common/src/main/resources/log4j2.xml, mnemonic-computing-services/mnemonic-utilities-service/src/main/resources/log4j2.xml, mnemonic-core/src/main/resources/log4j2.xml, mnemonic-examples/src/main/resources/log4j2.xml, mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-java-vmem-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-nvml-pmem-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-pmalloc-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-pmdk-pmem-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-pmdk-vmem-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-redis-service/src/main/resources/log4j2.xml, mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/resources/log4j2.xml, mnemonic-sessions/src/main/resources/log4j2.xml, mnemonic-spark/mnemonic-spark-core/src/main/resources/log4j2.xml
=> MNEMONIC-729: Configure the log4jv2.xml with correct settings that align with current log4jv1 settings

mnemonic-benches/pom.xml, mnemonic-collections/pom.xml, mnemonic-common/pom.xml, mnemonic-computing-services/pom.xml, mnemonic-core/pom.xml, mnemonic-examples/pom.xml, mnemonic-hadoop/pom.xml, mnemonic-memory-services/pom.xml, mnemonic-sessions/pom.xml, mnemonic-spark/pom.xml, pom.xml
=> MNEMONIC-730: Making the log4j related version configurable

mnemonic-benches/mnemonic-sort-bench/pom.xml, mnemonic-benches/pom.xml, mnemonic-collections/pom.xml, mnemonic-common/pom.xml, mnemonic-computing-services/mnemonic-utilities-service/pom.xml, mnemonic-computing-services/pom.xml, mnemonic-core/pom.xml, mnemonic-examples/pom.xml, mnemonic-hadoop/mnemonic-hadoop-mapreduce/pom.xml, mnemonic-hadoop/pom.xml, mnemonic-memory-services/mnemonic-java-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-nvml-pmem-service/pom.xml, mnemonic-memory-services/mnemonic-nvml-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-pmalloc-service/pom.xml, mnemonic-memory-services/mnemonic-pmdk-pmem-service/pom.xml, mnemonic-memory-services/mnemonic-pmdk-vmem-service/pom.xml, mnemonic-memory-services/mnemonic-redis-service/pom.xml, mnemonic-memory-services/mnemonic-sys-vmem-service/pom.xml, mnemonic-memory-services/pom.xml, mnemonic-sessions/pom.xml, pom.xml
Bump to 0.18 post 0.17 RC1 release
=> Bump version to 0.18-SNAPSHOT post 0.17 release

docker/docker-CentOS/Dockerfile, docker/docker-Fedora/Dockerfile, docker/docker-Ubuntu/Dockerfile
=> MNEMONIC-746: MAINTAINER instruction in Dockerfile is deprecated

.devcontainer/devcontainer.json
Add dev. container feature to the project.
=> MNEMONIC-747: Enable Dev. container feature

docker/docker-CentOS/Dockerfile, docker/docker-Fedora/Dockerfile, docker/docker-Ubuntu/Dockerfile
=> MNEMONIC-749: Add memkind library to Docker images

mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/common.c
=> MNEMONIC-752: Add common.c to memkind service

mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/config.h.in
=> MNEMONIC-754: Add config.h.in to memkind memory service

mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/org_apache_mnemonic_service_memory_internal_VMemServiceImpl.c
=> MNEMONIC-758: Add org_apache_mnemonic_service_memory_internal_VMemServiceImpl.c to memkind memory service

mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/native/common.c, mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/native/common.h
Create place holder for version  info
=> MNEMONIC-753: Design versioning logic to be added to Durable Object implementation

mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/CMakeLists.txt
=> MNEMONIC-763: Add CMakefile to memkind memory service for the compilation of native code

mnemonic-hadoop/mnemonic-hadoop-mapreduce/build.gradle
Signed-off-by: Zane <rhythmwind@hotmail.com>
=> MNEMONIC-759: Upgrade Hadoop version to remove the potential vulnerabilities

build.gradle
Signed-off-by: Zane <rhythmwind@hotmail.com>
=> MNEMONIC-760: Upgrade logbook version for potential security vulnerabilities

mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/VMemKindServiceImpl.java
=> MNEMONIC-765: Add VMemKind ServiceImpl to memkind memory service

build.gradle
Signed-off-by: Zane <rhythmwind@hotmail.com>
=> MNEMONIC-761: Upgrade version for Simple Logging Facade for Java due to potential security vulnerability

mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/CMakeLists.txt, mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/org_apache_mnemonic_service_memory_internal_VMemKindServiceImpl.c, mnemonic-memory-services/mnemonic-memkind-pmem-service/src/main/native/org_apache_mnemonic_service_memory_internal_VMemKindServiceImpl.h
=> MNEMONIC-766: Correct JNI class name from VMemServiceImpl to VMemKindServiceImpl

pom.xml
Signed-off-by: lcy0816 <lcy0816@hotmail.com>
=> MNEMONIC-770

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.devcontainer.yml, .gitignore
Add a dev container configuration for vscode
=> MNEMONIC-777 Add a dev container configuration for vscode

mnemonic-examples/src/main/java/org/apache/mnemonic/examples/CreateOrder.java
Refactored and Commented Apache Mnemonic Protocol HTTPS Code in Java for Enhanced Readability and Efficiency
=> MNEMONIC-804: Refactored and Commented Apache Mnemonic Protocol HTTPS Code in Java
