- mnemonic-memory-services/mnemonic-pmalloc-service/src/main/native/CMakeLists.txt
appended  /usr/local onto the current list of directories in CMakeList
> MNEMONIC-204: Fix issues with the pmalloc service on MacOS

- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMap.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapFactory.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/MapEntry.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/Person.java
- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
This pull request defines durable map data structure and basic operations- PUT, GET , DELETE and RESIZE.  
Implementation details:
Durable maps are implemented on memory chunks(buckets) where each memory allocated chunk stores a durable linkedlist.   Below figure shows a map with capacity 4 and size 3
|_bucket 1_____|  --->null
|_bucket 2_____| --->|______LinkedList elem1__|--->null
|_bucket 3_____|---->null
|_bucket 4_____|---->|______LinkedList elem1__|--->|______LinkedList elem2__|--->null
During instantiation of a durable map data structure,  the user can opt to choose initialCapacity as a constructor parameter to specify the number of buckets to be allocated.  If it is not provided, default map capacity(16) number of buckets are initially allocated. If map size exceeds a configurable …
> MNEMONIC-208: Adding PUT/GET/DELETE for durable maps.

- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
- mnemonic-core/src/main/java/org/apache/mnemonic/NonVolatileMemAllocator.java
Possible memory leaks are cleaned up when Linkedlist is removed.  Verified that there are no memory leaks with DurableHashMapNGTest
> MNEMONIC-215: Cleanup of memory leaks in Linkedlist implementation

- mnemonic-collections/pom.xml
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
Added missing testcases for having durable buffer/chunks as HashMap values
> MNEMONIC-105: Adding Testcases for durable buffers and chunks

- mnemonic-core/src/main/java/org/apache/mnemonic/GenericField.java
There will be memory leaks if resources are not restored during destroy of a generic field.
> MNEMONIC-233: Restore the resources before destroy of Generic Field

- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
Holder must be destroyed at last after destroying other fields.
> MNEMONIC-234: Reorder field destroy of a durable data structure

- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
Right offsets are provided for primitive type fields based on the field lengths.
> MNEMONIC-237: Incorrect offset for primitive type fields

- docker-ubuntu/Dockerfile
- docker-ubuntu/README.md
The existed Dockerfile has described how to setup Mnemonic development environment for CentOS only, so we need another one for Ubuntu, because the Ubuntu also is one of most popular server system.
> MNEMONIC-274 Add another Dockerfile for Ubuntu system

- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableArrayNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableSinglyLinkedListNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableTreeNGTest.java
- mnemonic-computing-services/mnemonic-utilities-service/src/test/java/org/apache/mnemonic/service/computingservice/DurableSinglyLinkedListNGPrintTest.java
- mnemonic-computing-services/mnemonic-utilities-service/src/test/java/org/apache/mnemonic/service/computingservice/DurableSinglyLinkedListNGSortTest.java
- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
- mnemonic-core/src/main/java/org/apache/mnemonic/EntityFactoryProxy.java
- mnemonic-core/src/main/java/org/apache/mnemonic/ParameterHolder.java
- mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapreduce/PersonListEFProxy.java
- mnemonic-spark/mnemonic-spark-core/src/test/java/org/apache/mnemonic/spark/PersonListEFProxy.java
Sub-task of MNEMONIC-276. Add overloaded methods for create and restore to handle optional parameters when creating/restoring durable class.
> MNEMONIC-280 Add overload methods to handle optional paramters

- docker/README.md
MNEMONIC-332: The Logo in docker page deprecated.
- Updated the logo in the docker's `README.md` to use the same in the project's `README.md`
> MNEMONIC-332: The Logo in docker page deprecated

- docker/docker-CentOS/Dockerfile
Assign a version number instead of "latest" for docker Centos build for compatibility concerns.
> MNEMONIC-353 Assign fixed version number to docker Centos build

- bin/release.sh
added error message and exit command to guard the tagging if failed.
> Fixed MNEMONIC-364: Add GPG failure handling in release script

- mnemonic-core/src/main/java/org/apache/mnemonic/ParameterHolder.java
Some test cases need to pass Pair as parameters when creating durable class. Current ParameterHolder class doesn't have the support for this feature.
> MNEMONIC-304 Add suppot for Pair to ParameterHolder class

- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArrayImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSetImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTreeImpl.java
- mnemonic-core/src/main/java/org/apache/mnemonic/Allocator.java
- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
- mnemonic-core/src/main/java/org/apache/mnemonic/ChunkBuffer.java
- mnemonic-core/src/main/java/org/apache/mnemonic/Durable.java
- mnemonic-core/src/main/java/org/apache/mnemonic/DurableBuffer.java
- mnemonic-core/src/main/java/org/apache/mnemonic/DurableChunk.java
- mnemonic-core/src/main/java/org/apache/mnemonic/GenericField.java
- mnemonic-core/src/main/java/org/apache/mnemonic/NonVolatileMemAllocator.java
- mnemonic-core/src/main/java/org/apache/mnemonic/Persistence.java
- mnemonic-core/src/main/java/org/apache/mnemonic/SysMemAllocator.java
- mnemonic-core/src/main/java/org/apache/mnemonic/VolatileMemAllocator.java
- mnemonic-core/src/main/java/org/apache/mnemonic/service/memory/NonVolatileMemoryAllocatorService.java
- mnemonic-core/src/main/java/org/apache/mnemonic/service/memory/VolatileMemoryAllocatorService.java
- mnemonic-memory-services/mnemonic-java-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/JavaVMemServiceImpl.java
- mnemonic-memory-services/mnemonic-nvml-pmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/PMemServiceImpl.java
- mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/VMemServiceImpl.java
- mnemonic-memory-services/mnemonic-pmalloc-service/src/main/java/org/apache/mnemonic/service/memory/internal/PMallocServiceImpl.java
- mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/SysVMemServiceImpl.java
Currently persist(), sync(), flush() calls are exposed to the user. This is confusing.  Only one call should be exposed to user that provides the default functionality.
> MNEMONIC-275 Implement a default function to sync data to the persisent storage

- mnemonic-memory-services/mnemonic-nvml-pmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/PMemServiceImpl.java
- mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/VMemServiceImpl.java
- mnemonic-memory-services/mnemonic-pmalloc-service/src/main/java/org/apache/mnemonic/service/memory/internal/PMallocServiceImpl.java
- mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/java/org/apache/mnemonic/service/memory/internal/SysVMemServiceImpl.java
Now we have several memory allocator service implementations such as pmalloc, pmem, javavmem. Once we instantiate a memory allocator service, it would try to load native library for all implementations. As a result, we should prepare all of those native library even if we only use one kind of memory service. Loading native library should be lazy.
> MNEMONIC-463: Should load native library in memory service lazily

- mnemonic-core/src/main/java/org/apache/mnemonic/EntityFactoryProxyHelper.java
For generic case, Mnemonic usually asks for factory proxy for each of generic type that generic class required to construct correct durable object correctly. but there are a couple of factory operations need to implemented and those operations are mostly repeated themselves. so we could construct a convenient class to simply it.
> MNEMONIC-455: Simply the Factory proxy construction

- mnemonic-examples/src/main/java/org/apache/mnemonic/examples/CreateOrder.java
The part of constructing Product's Factory Proxies could be simplified by using FactoryProxyHelper, so we can adjust the code to adopt this method.
> MNEMONIC-466: Simplify the example code of CreateOrder using FactoryProxyHelper

- mnemonic-examples/src/main/java/org/apache/mnemonic/examples/ShowOrder.java
This task is to simplify the example code of ShowOrder by using FactoryProxyHelper, similar to MNEMONIC-466
> MNEMONIC-467: Simplify the example code of ShowOrder by using FactoryProxyHelper

- mnemonic-core/src/main/java/org/apache/mnemonic/ParameterHolder.java
Added support for reclaim context in ParameterHolder class.
> MNEMONIC-389: ParameterHolder should contain reclaim context

- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableArrayImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashMapImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableHashSetImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableSinglyLinkedListImpl.java
- mnemonic-collections/src/main/java/org/apache/mnemonic/collections/DurableTreeImpl.java
- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
- mnemonic-core/src/main/java/org/apache/mnemonic/Durable.java
- mnemonic-core/src/main/java/org/apache/mnemonic/DurableBuffer.java
- mnemonic-core/src/main/java/org/apache/mnemonic/DurableChunk.java
- mnemonic-core/src/main/java/org/apache/mnemonic/GenericField.java
The reference breaking operation should be exposed by durable class for the developer to use. this function would break the reference of linked objects and release them if no more strong reference to them.
> MNEMONIC-481: Add reference breaking operation in Durable class

- mnemonic-core/src/main/java/org/apache/mnemonic/RefBreak.java
A durable class should support new annotation to mark the fields that would be broken when reference breaking operation is invoked.
> MNEMONIC-482:Support reference breaking mark on specified fields

- mnemonic-core/src/main/java/org/apache/mnemonic/AnnotatedDurableEntityClass.java
The functionality of reference breaking mark should be implemented to release memory resource from heap while keeping the durable object in non-volatile memory.
> MNEMONIC-486: Implement the functionality of reference breaking mark for general durable object

- mnemonic-core/src/main/java/org/apache/mnemonic/GenericField.java
The generic field should implement the refbreak() operation from the durable interface for releasing underlying resource from its heap.
> MNEMONIC-493: Implement the functionality of reference breaking mark for generic field

- docker/docker-Ubuntu/Dockerfile
The Dockerfile for Ubuntu contains the deployment of Maven that is installed via Apt, the ubuntu repository does not have the latest version of Maven so the installation instruction would be updated to deploy the latest version of Maven v3.5.4 manually to work with OpenJDK 10.
> MNEMONIC-505: update the Maven installation from repository to manually deployment

- mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/common/Person.java
- mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/common/PersonListEFProxy.java
- mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapred/MneMapredChunkDataTest.java
- mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapred/MneMapredLongDataTest.java
- mnemonic-hadoop/mnemonic-hadoop-mapreduce/src/test/java/org/apache/mnemonic/mapred/MneMapredPersonDataTest.java
Added chunk data, long data and person data test cases for mapred based following APIs,
1. MneInputFormat
2. MneMapredRecordReader
3. MneMapredRecordWriter
4. MneOutputFormat
These test cases are based on the test cases for mapreduce new APIs. However rewritten due to API changes.
> MNEMONIC-519: Add test cases for mapred based older Hadoop API

- bin/mnemonic-checkstyle.xml
- mnemonic-core/pom.xml
- mnemonic-memory-services/mnemonic-nvml-vmem-service/pom.xml
- pom.xml
The project building shows the following issue.
> ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project mnemonic-nvml-vmem-service: Failed during checkstyle configuration: cannot initialize module SuppressionFilter - Cannot set property 'file' to 'bin/suppressions.xml' in module SuppressionFilter: InvocationTargetException: Unable to find: bin/suppressions.xml -> [Help 1]
This PR fixes up that building error and upgrades the maven checkstyle plugin.
Fixes #122
> Fix SuppressionFilter initialization failure

- mnemonic-computing-services/mnemonic-utilities-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-nvml-pmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-pmalloc-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-pmdk-pmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-pmdk-vmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/native/CMakeLists.txt
- pom.xml
This PR fixes the undefined pthread_create issue and upgrade the version of maven antrun plugin
Fixes #123
> Fix undefined reference to pthread_create for native library building

- docker/docker-CentOS/Dockerfile
This PR updates the Docker file to install pmem packages from CentOS repos instead of building from its source.
Fixes #130
> Adopt pmem packages in CentOS docker file

- docker/docker-Ubuntu/Dockerfile
This PR updates the Docker file to install pmem packages from Ubuntu repos instead of building it from source. In addition, it upgraded the Ubuntu from 16.04 to 18.04 since the pmem packages seem not available to old Ubuntu distribution repo.
Fixes #129
> Adopt pmem packages in Ubuntu dockerfile

- docker/README.md
- docker/docker-Ubuntu/Dockerfile
This patch replaces the manually installation of Maven with apt install maven,
becaues the version of Maven of Ubuntu 18 is greater than v3.5.4.
The proxy settings for Maven also been removed to simplify the configuration.
The README file has been updated to reflect the changes to Dockerfiles.
Fixes #134
> Refactor the deployment of Maven in Ubuntu Dockerfile

- docker/docker-CentOS/Dockerfile
This patch replaces the manually installation of Maven with yum install maven,
becaues the version of Maven of CentOS 8 is already v3.5.4.
The proxy settings for Maven also been removed to simplify the configuration.
Fixes #135
> Refactor the deployment of Maven in CentOS Dockerfile

- build.gradle
This patch added all dependent artifacts to Gradle build script according to the section of dependencyManagement. 
I cannot verify the completeness for Gradle building for now, I think missing artifacts could be added later on demand.
> MNEMONIC-542: Configure the dependencyManagement artifacts of whole project

- mnemonic-common/build.gradle
This patch makes it compatible with Gradle 7 as well.
> MNEMONIC-546: Create build.gradle for subproject mnemonic-common

- mnemonic-core/build.gradle
The test cases of mnemonic-core needs to get annotation processing from the its own sub-project. there is a testAnnotationProcessor instruction that has been supported by Gradle to handle it.
> MNEMONIC-552 Enable annotation processing for the test cases of mnemonic-core

- gradle/wrapper/gradle-wrapper.properties
- mnemonic-computing-services/mnemonic-utilities-service/build.gradle
- mnemonic-examples/build.gradle
- mnemonic-memory-services/mnemonic-java-vmem-service/build.gradle
- mnemonic-memory-services/mnemonic-nvml-pmem-service/build.gradle
- mnemonic-memory-services/mnemonic-nvml-vmem-service/build.gradle
- mnemonic-memory-services/mnemonic-pmalloc-service/build.gradle
- mnemonic-memory-services/mnemonic-pmdk-pmem-service/build.gradle
- mnemonic-memory-services/mnemonic-pmdk-vmem-service/build.gradle
- mnemonic-memory-services/mnemonic-sys-vmem-service/build.gradle
- mnemonic-query/build.gradle
Fix "dependency" has been deprecated warning in Gradle 7 and upgraded to latest Gradle.
> MNEMONIC-548: Fix deprecated warning in gradle 7

- build.gradle
The Gradle build shows the following warnings that needs to be addressed
Using insecure protocols with repositories has been deprecated. This is scheduled to be removed in Gradle 7.0. Switch Maven repository 'maven(http://repo.maven.apache.org/maven2)' to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/6.6.1/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details.
> MNEMONIC-551:Switch insecure protocols to secure ones

- mnemonic-memory-services/mnemonic-sys-vmem-service/build.gradle
> MNMONIC-560: Fix unexpected '}' in build.gradle of mnemonic-sys-vmem-service

- mnemonic-collections/build.gradle
It is similar to enable annotation processing for the test cases of mnemonic-core. but this ticket asks for applying it on durable collections under this subproject.
> MNEMONIC-540: Enable annotation processing for mnemonic-collections

- mnemonic-memory-services/mnemonic-nvml-vmem-service/build.gradle
This memory service relies on a native code to work, it does rely on external persistent memory libraries to work. it is a challenge task to deploy the external library and build it.
Local build passed
./gradlew :mnemonic-memory-service:mnemonic-nvml-vmem-service:clean -x test
BUILD SUCCESSFUL in 648ms
3 actionable tasks: 3 executed
./gradlew :mnemonic-memory-service:mnemonic-nvml-vmem-service:build -x test
BUILD SUCCESSFUL in 1s
10 actionable tasks: 6 executed, 4 up-to-date
> MNEMONIC-562: Complete the build of mnemonic-nvml-vmem-service

- mnemonic-benches/mnemonic-sort-bench/build.gradle
- mnemonic-benches/mnemonic-spark-kmeans-bench/build.gradle
- mnemonic-hadoop/mnemonic-hadoop-mapreduce/build.gradle
- mnemonic-sessions/build.gradle
- mnemonic-spark/mnemonic-spark-core/build.gradle
- settings.gradle
There are several sub projects missing in settings.gradle, i.e. mnemonic-benches, mnemonic-sessions, mnemonic-spark, mnemonic-hadoop. those need to be added to Gradle settings file for building.
> MNEMONIC-574: Add missing sub projects to settings.gradle

- mnemonic-examples/build.gradle
convert mnemonic-example build from maven to gradle as other subproject folders
> MNEMONIC-568 Create build.gradle for subproject mnemonic-examples

- mnemonic-computing-services/mnemonic-utilities-service/build.gradle
There is a computing service needs to get built with Gradle. Its structure is similar to mnemonic memory service so we can refer to their build.gradle files to complete this ticket.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
BUILD SUCCESSFUL in 10s
15 actionable tasks: 8 executed, 7 up-to-date
> MNEMONIC-566: Complete the Gradle build for mnemonic-utilities-service in mnemonic-computing-services

- mnemonic-examples/build.gradle
- mnemonic-examples/pom.xml
- mnemonic-examples/src/main/java/org/apache/mnemonic/examples/CreateOrder.java
- mnemonic-examples/src/main/java/org/apache/mnemonic/examples/HelloWorld.java
- mnemonic-examples/src/main/java/org/apache/mnemonic/examples/Main.java
- mnemonic-examples/src/main/java/org/apache/mnemonic/examples/ShowOrder.java
> MNEMONIC-599: Replace the Utils.getVolatileMemoryAllocatorService call from Example

- mnemonic-collections/build.gradle
- mnemonic-collections/pom.xml
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableArrayNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashSetNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurablePersonNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableSinglyLinkedListNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableSinglyLinkedListWithParamHolderNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableTreeNGTest.java
> MNEMONIC-603: Replace the Utils.getNonVolatileMemoryAllocatorService from Collections

- mnemonic-benches/mnemonic-sort-bench/build.gradle
- mnemonic-benches/mnemonic-sort-bench/src/main/java/org/apache/mnemonic/bench/DNCSTextFileSort.java
- mnemonic-benches/pom.xml
> MNEMONIC-605: Replace the Utils.getVolatileMemoryAllocatorService from Benches

- mnemonic-computing-services/mnemonic-utilities-service/src/test/java/org/apache/mnemonic/service/computing/DurableSinglyLinkedListNGPrintTest.java
- mnemonic-computing-services/mnemonic-utilities-service/src/test/java/org/apache/mnemonic/service/computing/DurableSinglyLinkedListNGSortTest.java
> MNEMONIC-606: Replace the Utils.getNonVolatileMemoryAllocatorService call from Computing Service

- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableArrayNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashMapNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableHashSetNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurablePersonNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableSinglyLinkedListNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableSinglyLinkedListWithParamHolderNGTest.java
- mnemonic-collections/src/test/java/org/apache/mnemonic/collections/DurableTreeNGTest.java
> MNEMONIC-621: Add Utils.getNonVolatileMemoryAllocatorService call back to Collections

- mnemonic-computing-services/mnemonic-utilities-service/src/test/java/org/apache/mnemonic/service/computing/DurableSinglyLinkedListNGPrintTest.java
- mnemonic-computing-services/mnemonic-utilities-service/src/test/java/org/apache/mnemonic/service/computing/DurableSinglyLinkedListNGSortTest.java
> MNEMONIC-623: Add Utils.getNonVolatileMemoryAllocatorService call back to Computing Service

- settings.gradle
- tools/source-assembly.xml
update both web assembly and gradle setting file to remove query module.
> MNEMONIC-655: Remove redundant module from source assembly

- build.gradle
- tools/source-assembly.xml
source-assembly.xml has been updated to exclude gradle and gradlew
Version is also updated in build.gradle
> MNEMONIC-657: Mnemonic release script should be updated to remove compiled code files in prepared release candidates

- mnemonic-spark/pom.xml
> MNEMONIC-665:Fix non-supported forkmode and java.ext.dirs in Spark test suites

- mnemonic-memory-services/mnemonic-redis-service/build.gradle
- mnemonic-memory-services/mnemonic-redis-service/pom.xml
- mnemonic-memory-services/mnemonic-redis-service/src/main/java/org/apache/mnemonic/service/memory/internal/RedisServiceImpl.java
- mnemonic-memory-services/mnemonic-redis-service/src/main/resources/META-INF/services/org.apache.mnemonic.service.memory.NonVolatileMemoryAllocatorService
- mnemonic-memory-services/mnemonic-redis-service/src/main/resources/log4j.properties
- mnemonic-memory-services/pom.xml
For redis integration into mnemonic as backend storage, we need to add the redis memory service to the project
> MNEMONIC-703: Add redis memory service in mnemonic project

- mnemonic-core/src/main/java/org/apache/mnemonic/Utils.java
Keep thread information when get InterruptedException
Signed-off-by: chenyang <chenyang@apache.org>
> MNEMONIC-725:Keep thread information when get InterruptedException

- .gitignore
- .vscode/settings.json
This PR adds initial settings folder and ignore dccode file accordingly.
> MNEMONIC-726: Adding initial version of VSCode settings

- pom.xml
This PR excludes .dccache file from license checklist.
> MNEMONIC-732: Exclude dccache from license check

- gradle/wrapper/gradle-wrapper.properties
> MNEMONIC-738: gradle build error caused by updated class major version

- mnemonic-benches/pom.xml
- pom.xml
- settings.gradle
- tools/source-assembly.xml
- tools/test.conf
The whole spark module is excluded temporarily from our build system.
I had to add spark into exclude list of Apache Ant, otherwise it reported license error on those excluded directory.
> MNEMONIC-733: identified 5 more critical security vulnerabilities

- mnemonic-computing-services/mnemonic-utilities-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-nvml-pmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-nvml-vmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-pmalloc-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-pmdk-pmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-pmdk-vmem-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-redis-service/src/main/native/CMakeLists.txt
- mnemonic-memory-services/mnemonic-sys-vmem-service/src/main/native/CMakeLists.txt
Increase the minimum version requirement of CMake from 2.8.11 to 3.12 to suppress the `Compatibility with CMake < 2.8.12` warning on Ubuntu 22.04.
> MNEMONIC-744: CMake Deprecation Warning
